Product model#2
illuminatedspace/timeshare pull request #6
Opened 2017-02-28 22:01 UTC by luisamiranda

Preliminary model created

2017-02-28 22:39 UTC, illuminatedspace requested changes
I think there are some changes to make.

2017-02-28 22:39 UTC, illuminatedspace commented on db/models/product.js
> +        isUnique: true,
isUnique is not a validator. I think we need to do this in the route.

2017-02-28 22:39 UTC, illuminatedspace commented on db/models/product.js
> +        defaultValue: 'https://pixabay.com/photo-1752164/',
Terrifying stock photo. Ace choice.

2017-03-01 15:47 UTC, luisamiranda commented on db/models/product.js
> +        isUnique: true,
excellent point. removed.

2017-03-01 16:14 UTC, illuminatedspace approved these changes
Approved!

2017-03-01 16:14 UTC, illuminatedspace commented on db/models/product.js
> +module.exports = Product
I think that you might want to set up your associations in the index folder.

2017-03-01 16:14 UTC, merged